#------------ STAGE:1 - BUILD ---------------

FROM python:3.11  as builder

WORKDIR /app

RUN apt-get update && \
    apt-get install -y sqlite3 && \
    apt-get clean

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt


#------------ STAGE:2 FINAL STAGE --------------

FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y sqlite3 && \
    apt-get clean

COPY --from=builder /usr/local/lib/python3.11/site-packages/ /usr/local/lib/python3.11/site-packages/

COPY . .

CMD ["python", "app.py"]
